name: Docker Image CI for GHCR and ACR

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      CONTAINER_REGISTRY_UN: ${{ secrets.CONTAINER_REGISTRY_UN }}
      CONTAINER_REGISTRY_PW: ${{ secrets.CONTAINER_REGISTRY_PW }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Spring Boot application (Maven)
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u rujul13 --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/rujul13/arithmetic-service:1 .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/rujul13/arithmetic-service:1

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.AZURE_CONTAINER_REGISTRY }} | docker login practicumsruj.azurecr.io --username practicumsruj --password-stdin

      - name: Tag and push Docker image to Azure Container Registry
        run: |
          docker tag ghcr.io/rujul13/arithmetic-service:1 practicumsruj.azurecr.io/arithmetic-service:1
          docker push practicumsruj.azurecr.io/arithmetic-service:1

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Deploy
        run: ./deploy.sh
